-- Query 1--
SELECT F_NAME, L_NAME FROM EMPLOYEES
	WHERE ADDRESS LIKE '%Elgin,IL%';
	
--Query 2--
SELECT F_NAME, L_NAME FROM EMPLOYEES
	WHERE B_DATE LIKE '197%';
	
--Query 3--
SELECT * FROM EMPLOYEES
	WHERE DEP_ID = 5 AND (SALARY BETWEEN 60000 AND 70000);

--Query 4A--
SELECT F_NAME, L_NAME, DEP_ID FROM EMPLOYEES
	ORDER BY DEP_ID;

--Query 4B--
SELECT F_NAME, L_NAME, DEP_ID FROM EMPLOYEES
	ORDER BY DEP_ID desc, L_NAME desc;

-- Query 5A--
SELECT DEP_ID, COUNT(*) FROM EMPLOYEES
	GROUP BY DEP_ID;

-- Query 5B--
SELECT DEP_ID, COUNT(*), AVG(SALARY) FROM EMPLOYEES
	GROUP BY DEP_ID;

-- Query 5C--
SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
	FROM EMPLOYEES
	GROUP BY DEP_ID;

-- Query 5D--
SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
	FROM EMPLOYEES
	GROUP BY DEP_ID ORDER BY AVG_SALARY;

-- Query 5E--
SELECT DEP_ID, COUNT (*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
	FROM EMPLOYEES
	GROUP BY DEP_ID  HAVING COUNT(*) < 4 ORDER BY AVG_SALARY;
	
-- BONUS Query 6E--
SELECT D.DEP_NAME, E.F_NAME, E.L_NAME 
	FROM EMPLOYEES as E, DEPARTMENTS as D 
	WHERE E.DEP_ID = D.DEPT_ID_DEP
	ORDER BY D.DEP_NAME, E.L_NAME desc;
	



